apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: todo-app
type: Opaque
stringData:
  # Shared secret for HS256
  secret_key: "93ueoC36OvBqfcLIx+xXt+XnV3vbWiI7XFsbZs9nobE="
  gemini_api_key: "AIzaSyBkHQ3AZlHPcvM_M1i792vAzIY6WpzdB30"
  better_auth_url: "http://localhost:3000"
