from typing import Protocol, List, Optional
from todo_app.domain.task import Task

class TaskRepository(Protocol):
    def add(self, task: Task) -> Task: ...
    def get(self, task_id: str) -> Optional[Task]: ...
    def get_all(self) -> List[Task]: ...
    def update(self, task: Task) -> Task: ...
    def delete(self, task_id: str) -> None: ...
    def delete_all(self) -> None: ...