apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: todo-app
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "notification-service"
        dapr.io/app-port: "8002"
    spec:
      containers:
      - name: notification-service
        image: notification-service:v5.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: connectionString
        - name: SMTP_HOST
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: smtp_host
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: smtp_user
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-credentials
              key: smtp_password
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: todo-app
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
